### ISSUE TITLE
Manglende environment variable?

### ISSUE THREAD

**Issue by v0nNemizez** [SteinTokvam/PowerPrices#1]
Ser ut som at Dockerfilen din mangler en environment variable. Kan kanksje sette dette via. config eller no sånt :)

Stacktrace:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

**Caused by: java.lang.NullPointerException: getenv("zone") must not be null**

**Comment by SteinTokvam** [comment]
Jeg har bare sendt det med når en kjører opp applikasjonen, men er sikkert en bedre måte å gjøre det på.
